---
output:                                       html_document
editor_options:
  chunk_output_type: console
---


# SIMULATIONS

## doing simulations of choice, generating tables and figures

```{r}
## Menus of options for simulations

# menu of options

scaling<-4

# attraction menus

options_a<-rbind(c(6, 4, 4, 6, 6, 3.4),c(4, 6, 6, 4, 3.4, 6))/scaling

#similarity menus

options_s<-rbind(c(6, 4, 4, 6, 3.8, 6.2), c(4, 6, 6, 4, 6.2, 3.8))/scaling


#compromise menus

options_c<-rbind(c(6, 4, 4, 6, 8, 2), c(4, 6, 6, 4, 2, 8))/scaling


options<-rbind(options_a,options_s,options_c)

## parameters for simulations

I<-1; m<-2; lam<-0.5; gamma<-3; beta<-1; k<-1; alpha<-1; stay<-1; tau<-0.1;
```

## make a choice what effect you want to graph

```{r}
# make a choice what effect you want to graph
# here we choose to graph the attraction effect, and put other effects under comments

effect<-"attraction" # for attraction effect
option<-options_a

#effect<-"similarity"
#option<-options_s

#effect<-"compromise"
#option<-options_c
```

## generate simulated data

```{r}
# generate simulated data

J<-length(option[,1])

# number of simulated choices

N<-200000

# obtain simulated first and second choices

rt_test<-matrix(data=1,nrow=J*N,ncol=14)
for (j in (1:J)){
for (i in (1:N)) {
  rt_test[(i+N*(j-1)),9:14]<-option[j,];
  rt_test[(i+N*(j-1)),1:4]<-lba_rng(rt_test[(i+N*(j-1)),9:14],k,I,m,lam,gamma,beta,stay,tau,alpha)
  }
  }

# save simulated choices

if(effect=="attraction"){rt_test_a<-rt_test}else{if(effect=="similarity"){rt_test_s<-rt_test}else{{rt_test_c<-rt_test}}}
```

## graphing shares and generating tables of transition

```{r}
# choice shares over time, using the "share_graph" function


share_graph(rt_test,effect)

## tables of simulated choices, with shares of first choice, revision pattern, and shares after revision, using share_table function


share_table(rt_test, effect)

```

