

### first, get all the markup levels from the appropriate data
# markups
markups <- read_csv("Data/alldata_exp2.csv") %>% 
  mutate(chosen = capitalize(chosen),
         type = capitalize(type)) %>%
  mutate(type = if_else(type == "Decoy", "Attraction", type)) %>% 
  mutate(type = if_else(type == "Compromise", "Reverse Compromise", type)) %>% 
  filter(type != "2menu") %>% 
  mutate(type = as.factor(type),
         type = fct_relevel(type, "Attraction", "Similarity")) %>% 
  mutate(chosen = as.factor(chosen),
         chosen = fct_relevel(chosen, "Target", "Competitor"))%>% 
  mutate(expected = case_when(type == "Attraction" ~ 0.5,
                              TRUE ~ 0.33)) %>% 
  mutate(markup = cut(targ_adv, breaks = c(0, 0.99, 1.01, 2), labels = c("Target 10% better", "Same price", "Target 10% worse")),
         markup = fct_relevel(markup, "Target 10% better", "Same price")) %>% 
  select(screen, type, markup) %>% 
  distinct()

df <- df %>% 
  left_join(markups, by = c("screen", "type"))

# the plots are generated by this function to save in copy-pasting code.
plot_by_markup <- function(effect){
  
  plotme <- df %>% 
    filter(type %in% effect) %>% 
    group_by(type, time, level, subject, chosen, markup, .drop = F) %>% 
    tally() %>% 
    filter(!is.na(chosen)) %>% 
    group_by(type, level, markup, time, subject) %>% 
    mutate(share = n/sum(n)) %>% 
    filter(!is.nan(share)) %>% 
    mutate(type = paste0(type, " effect")) %>% 
    group_by(type, level, markup, time, chosen, .drop = F) %>% 
    summarise(mean = mean(share, na.rm = TRUE),
              sd = sd(share, na.rm = TRUE),
              n = n(),
              se = sd/sqrt(n()),
              confintmult = qt(.95/2 + .5, n()),
              ci = se*confintmult) %>% 
    mutate(expected = case_when(type == "Attraction effect" ~ 0.5,
                                TRUE ~ 0.33)) %>% 
    mutate(level = as.factor(level),
           level = fct_relevel(level, "First click"))%>% 
    arrange(time, chosen) %>% 
    mutate(comparisons = case_when(chosen == "Target" & markup == "Target 10% better" ~ "10% cheaper",
                                   chosen == "Competitor" & markup == "Target 10% worse" ~ "10% cheaper",
                                   chosen == "Decoy" & markup == "Target 10% worse" ~ "10% cheaper",
                                   markup == "Same price" ~ "Same price",
                                   chosen == "Target" & markup == "Target 10% worse" ~ "10% more expensive",
                                   chosen == "Competitor" & markup == "Target 10% better" ~ "10% more expensive",
                                   chosen == "Decoy" & markup == "Target 10% better" ~ "10% more expensive"
    ))
  
  plotme <- plotme %>% 
    mutate(comparisons = fct_relevel(comparisons, "10% cheaper", "Same price"))
  
  if (effect == "Attraction") {
    plotme <- plotme %>% 
      filter(chosen != "Decoy") %>% 
      filter(!is.na(level)) 
  }
  
  ## creating the right comparisons
  # plotme <- plotme %>% 
  #   filter(chosen != "Decoy") %>% 
  #   ungroup() %>% 
  #   mutate(comparisons = case_when(chosen == "Target" & markup == "Target worse" ~ "10% less",
  #                                  chosen == "Competitor" & markup == "Target better" ~ "10% less",
  #                                  markup == "Same price" ~ "Same price",
  #                                  chosen == "Target" & markup == "Target better" ~ "10% more",
  #                                  chosen == "Competitor" & markup == "Target worse" ~ "10% more")) %>% 
  #   mutate(comparisons = fct_relevel(comparisons, "10% less", "Same price"))
  if (effect == "Attraction") {
    plotme_diff <- plotme %>%  
      filter(!is.na(level)) %>% 
      ungroup() %>% 
      filter(chosen != "Decoy") %>%   
      select(-markup) %>% 
      group_by(level, comparisons) %>% 
      select(time, chosen, level, mean, ci, comparisons) %>% 
      pivot_wider(names_from = chosen, values_from = c(mean, ci)) %>% 
      mutate(mean = mean_Target - mean_Competitor, 
             ci = ci_Target)
  }
  
  # if (effect == "Reverse Compromise" | effect == "Similarity") {
  #   plotme_diff <- plotme %>%  
  #     filter(!is.na(level)) %>% 
  #     ungroup() %>% 
  #     select(-markup) %>% 
  #     group_by(level, comparisons) %>% 
  #     select(time, chosen, level, mean, ci, comparisons) %>% 
  #     pivot_wider(names_from = chosen, values_from = c(mean, ci)) %>% 
  #     mutate(mean = mean_Decoy - mean_Target, 
  #            ci = ci_Target)    
  # }
  if (effect == "Reverse Compromise" | effect == "Similarity") {
    plotme_diff <- plotme %>%  
      filter(!is.na(level)) %>% 
      ungroup() %>% 
      select(-markup) %>% 
      group_by(level, comparisons) %>% 
      select(time, chosen, level, mean, ci, comparisons) %>% 
      pivot_wider(names_from = chosen, values_from = c(mean, ci)) %>% 
      mutate(mean = mean_Target - mean_Competitor, 
             ci = ci_Target)    
  }
  
  p1 <- plotme %>% 
    mutate(comparisons = fct_relevel(comparisons, "10% cheaper", "Same price")) %>% 
    mutate(ci = if_else(level == "All clicks", ci, NA_real_)) %>% 
    ggplot(aes(time, mean, color = chosen, linetype = level))+
    geom_errorbar(width = 0.25, aes(ymin=mean-ci, ymax=mean+ci), size = 0.3, alpha = 0.2)+
    geom_line(size=1)+
    geom_hline(aes(yintercept = expected), color='grey60', linetype='dashed')+
    scale_y_continuous(labels = scales::percent)+
    scale_x_continuous(labels = scales::trans_breaks(function(x) x/10, function(x) x/1),
                       limits = c(0,200))+
    scale_linetype_manual(name = "", values = c("twodash", "solid"))+
    labs(y = "Choice Share", x = "Seconds", 
         title = paste0(effect, " effect"))+
    coord_cartesian(ylim = c(0,1))+
    facet_grid(.~comparisons)+
    theme_ipsum()+
    theme(legend.position = "bottom",
          panel.grid.minor = element_blank(), 
          plot.title.position = "plot",
          plot.background = element_rect(fill = "white", color = "white"),
          plot.title = element_markdown(size = 14),
          strip.text = element_text(face = "bold", size = 13),
          # this part here below deletes stuff to better blend when pasted with diff plot
          axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          plot.margin = unit(c(0,0,0.5,0), 'cm'))+
    if (effect == "Attraction") {
      scale_color_manual(name = "", values = c("#4DAF4A", "#377EB8"))
    } else {
      scale_color_brewer(name = "", palette= "Set1", direction = -1)
    }
  
  
  
  p2 <- plotme_diff %>% 
    mutate(comparisons = fct_relevel(comparisons, "10% cheaper", "Same price")) %>% 
    mutate(ci = if_else(level == "All clicks", ci, NA_real_)) %>% 
    ggplot(aes(time, mean, group = level, linetype = level))+
    geom_errorbar(width = 0.25, aes(ymin=mean-ci, ymax=mean+ci), size = 0.3, alpha = 0.2)+
    geom_line(size=1)+
    scale_y_continuous(labels = scales::percent)+
    scale_x_continuous(labels = scales::trans_breaks(function(x) x/10, function(x) x/1))+
    scale_linetype_manual(name = "", values = c("twodash", "solid"))+
    geom_hline(yintercept = 0, color = "red", linetype = "dashed")+
    facet_grid(.~comparisons)+
    coord_cartesian(ylim = c(-0.25,0.5))+
    labs(y = "Difference", x = "Seconds")+
    theme_ipsum()+
    theme(legend.position = "bottom",
          panel.grid.minor = element_blank(), 
          plot.title.position = "plot",
          plot.background = element_rect(fill = "white", color = "white"),
          strip.text = element_blank(),
          strip.background = element_blank(),
          plot.title = element_markdown(size = 16),
          plot.margin = unit(c(0,0,0,0), 'cm'))
  
  p1/p2 + plot_layout(heights = c(2.2,1), guides = "collect") & 
    theme(legend.position = "bottom", legend.margin = margin(0,0,0,0),
          legend.text = element_text(size = 15))
  
  name = ifelse(effect == "Attraction", 
                "Figure_9", 
                ifelse(effect == "Similarity", 
                       "Figure_10", 
                       "Figure_11"))
  
  ggsave(paste0("Figures/", name, ".png"), width = 16/1.6, height = 9/1.6, units = "in", dpi = 300)
}

# calls to the function to generate the plots
plot_by_markup(c("Attraction"))
plot_by_markup(c("Reverse Compromise"))
plot_by_markup(c("Similarity"))